---
- name: add sudo group
  group: name=sudo state=present
  tags: users

- name: add individual users
  user: name={{ item }} createhome=yes groups=sudo shell=/bin/bash state=present
  with_items: "{{ users }}"
  tags: users

- name: add authorized keys
  authorized_key: user={{ item }} key="{{ lookup('file', '../keys/' + item + '.pub') }}"
  with_items: "{{ users }}"
  tags: users
